[tools]
	bun  = "1.3.0"
	node = "22.21.0"

[tasks.dev]
	run = "bun dev"
[tasks.build]
	run = "bun run build"
[tasks.preview]
	run = "bun preview"

[env]
	_.path = [
		'{{config_root}}/node_modules/.bin',
	]
